name: Expo CI

on:
  push:
    branches:
      - staging
      - production

jobs:
  build-or-update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v2

      - name: ğŸŒ Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: ğŸ§¶ Install Project Dependencies
        run: yarn install

      - name: ğŸš€ Cache Dependencies for Faster Builds
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: ğŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: ğŸ— Setup EAS local builds
        run: yarn global add eas-cli-local-build-plugin

      - name: ğŸ Build & Submit iOS App
        run: |
          eas build --platform ios --non-interactive --local --profile ${{ github.ref_name }} --output ./artifacts/${{ github.ref_name }}.ipa
          eas submit --platform ios --profile ${{ github.ref_name }} --path ./artifacts/${{ github.ref_name }}.ipa

      # - name: ğŸ¤– Build & Submit Android App
      #   run: |
      #     eas build --platform android --non-interactive --local --profile ${{ github.ref_name }}  --output ./artifacts/${{ github.ref_name }}.apk
      #     eas submit --platform android --profile ${{ github.ref_name }} --path ./artifacts/${{ github.ref_name }}.apk

      # - name: ğŸ”„ Push EAS Update
      #   run: eas update --branch ${{ github.ref_name }}
