name: Expo CI

on:
  push:
    branches:
      - staging
      - production

jobs:
  build-or-update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v2

      - name: ğŸŒ Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: ğŸ§¶ Install Project Dependencies
        run: yarn install

      - name: ğŸš€ Cache Dependencies for Faster Builds
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: ğŸ” Check for App Version Change
        id: version-check
        run: |
          VERSION_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'app.json')
          if [[ "$VERSION_CHANGED" != "" ]]; then
            echo "::set-output name=version_changed::true"
          else
            echo "::set-output name=version_changed::false"
          fi

      - name: ğŸ Build & Submit iOS App
        if: steps.version-check.outputs.version_changed == 'true'
        run: |
          eas build --platform ios --non-interactive --local --profile ${{ github.ref_name }} --output ./artifacts/${{ github.ref_name }}.ipa
          eas submit --platform ios --profile ${{ github.ref_name }} --path ./artifacts/${{ github.ref_name }}.ipa

      # - name: ğŸ¤– Build & Submit Android App
      #   if: steps.version-check.outputs.version_changed == 'true'
      #   run: |
      #     eas build --platform android --non-interactive --local --profile ${{ github.ref_name }}  --output ./artifacts/${{ github.ref_name }}.apk
      #     eas submit --platform android --profile ${{ github.ref_name }} --path ./artifacts/${{ github.ref_name }}.apk

      - name: ğŸ”„ Push EAS Update
        if: steps.version-check.outputs.version_changed == 'false'
        run: eas update --branch ${{ github.ref_name }}
